<?php

/**
 * @file
 * Control the group and group content view access of groups by custom logic.
 */

/**
 * Implements hook_entity_info().
 */
function og_arbitrary_access_entity_info() {
  $items['og_arbitrary_access'] = array(
    'label' => t('OG arbitrary access'),
    'controller class' => 'EntityAPIController',
    'entity class' => 'OgArbitraryAccess',
    'base table' => 'og_arbitrary_access',
    'fieldable' => TRUE,
    'access callback' => 'og_arbitrary_access_access',
    'entity keys' => array(
      'id' => 'id',
      'label' => FALSE,
      'bundle' => 'type',
      'language' => 'language',
    ),
    'bundles' => array(),
    'bundle keys' => array(
      'bundle' => 'name',
    ),
    'view modes' => array(
      'full' => array(
        'label' => t('Full'),
        'custom settings' => FALSE,
      ),
    ),
    'module' => 'og_arbitrary_access',
    'metadata controller class' => 'EntityDefaultMetadataController',
    'views controller class' => 'EntityDefaultViewsController',
    'entity cache' => module_exists('entitycache'),
  );

  // Add bundles by plugins.
  foreach (og_arbitrary_access_get_og_arbitrary_access_plugins() as $plugin_name=> $plugin) {
    $items['og_arbitrary_access']['bundles'][$plugin_name] = array(
      'label' => $plugin['label'],
      'admin' => array(
        'path' => 'admin/structure/og_arbitrary_access/manage/%og_arbitrary_access',
        'real path' => 'admin/structure/og_arbitrary_access/manage/' . $plugin_name,
        'bundle argument' => 4,
        'access arguments' => array('administer og arbitrary access types'),
      ),
    );
  }

  return $items;
}

/**
 * Implements hook_og_fields_info().
 */
function og_arbitrary_access_og_fields_info() {
  $items['og_arbitrary_access'] = array(
    'type' => array('group', 'group_content'),
    'description' => t('Reference to OG arbitrary access entities.'),
    'field' => array(
      'field_name' => 'og_arbitrary_access',
      'type' => 'entityreference',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'settings' => array(
      ),
    ),
    'instance' => array(
      'label' => t('OG arbitrary access'),
      'description' => t('Reference to OG arbitrary access entities.'),
      'default_value' => array(0 => array('value' => 1)),
    ),
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function og_arbitrary_access_ctools_plugin_directory($module, $plugin) {
  if ($module == 'og_arbitrary_access') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function og_arbitrary_access_ctools_plugin_type() {
  $plugins['og_arbitrary_access'] = array(
    'classes' => array('class'),
    'process' => 'og_arbitrary_access_plugin_process',
  );
  return $plugins;
}


/**
 * Add defaults values to the normalizer related plugins.
 */
function og_arbitrary_access_plugin_process(&$plugin, $info) {
  // Common operations.
  $plugin += array(
    'description' => '',
  );

  // Call the plugin specific process functions.
  $function = 'og_arbitrary_access_process_' . $info['type'];
  if (function_exists($function)) {
    $function($plugin, $info);
  }
}

/**
 * Include CTools plugins and get all normalizer plugins.
 *
 * @return array
 *   All normalizing plugins.
 */
function og_arbitrary_access_get_og_arbitrary_access_plugins() {
  ctools_include('plugins');
  return ctools_get_plugins('og_arbitrary_access', 'og_arbitrary_access');
}

/**
 * Include CTools plugins and get the specified electricity normalizer plugin.
 *
 * @param string $plugin_name
 *   If provided this function only returns the selected plugin.
 *
 * @return array
 *   The selected plugin for electricity normalizer.
 */
function og_arbitrary_access_get_og_arbitrary_access_plugin($plugin_name) {
  ctools_include('plugins');
  return ctools_get_plugins('og_arbitrary_access', 'og_arbitrary_access', $plugin_name);
}

/**
 * Return the handler based on major and minor version, and resource name.
 *
 * @param $plugin_name
 *  Name of plugin.
 * @param $node
 *   The node object.
 *
 * @throws Exception
 *  Class not found.
 *
 * @return OgArbitraryAccessInterface
 *   The handler object.
 */
function og_arbitrary_access_get_og_arbitrary_access_handler($plugin_name, $node) {
  $cache = &drupal_static(__FUNCTION__);
  if (isset($cache[$plugin_name])) {
    return $cache[$plugin_name];
  }

  $cache[$plugin_name] = NULL;

  ctools_include('plugins');
  $plugin = ctools_get_plugins('og_arbitrary_access', 'og_arbitrary_access', $plugin_name);
  if (!$class = ctools_plugin_load_class('og_arbitrary_access', 'og_arbitrary_access', $plugin_name, 'class')) {
    throw new \Exception("OG access plugin class for '$plugin_name' not found.");
  }
  $handler = new $class($plugin, $node);
  $cache[$plugin_name] = $handler;

  return $cache[$plugin_name];
}


/**
 * Implements hook_node_grants().
 */
function og_arbitrary_access_node_grants($account, $op) {
  $grants = array();
  foreach (og_arbitrary_access_get_og_arbitrary_access_plugins() as $plugin_name => $plugin) {
    $result = call_user_func(array($plugin['class'], 'getNodeGrants'), $account, $op);
    $grants = array_merge_recursive($grants, $result);
  }

  return $grants;
}

/**
 * Implements hook_node_access_records().
 */
function og_arbitrary_access_node_access_records($node) {
  $grants = array();
  foreach (og_arbitrary_access_get_og_arbitrary_access_plugins() as $plugin_name => $plugin) {
    $handler = og_arbitrary_access_get_og_arbitrary_access_handler($plugin_name, $node);
    $result = $handler->getNodeAccessRecords();
    $grants = array_merge_recursive($grants, $result);
  }

  dpm($grants);

  return $grants;
}
